---
- name: Test Connectivity
  hosts: all
  gather_facts: false

  tasks:
    - name: Ping target host
      ping:

    - name: Show hostname
      command: hostname
      register: hostname_output

    - debug:
        var: hostname_output.stdout