---
- name: Install and Run Speedtest
  hosts: all
  become: true

  tasks:
    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Install speedtest-cli
      pip:
        name: speedtest-cli

    - name: Run speed test
      command: speedtest-cli --simple
      register: result
      changed_when: false

    - name: Show result
      debug:
        var: result.stdout_lines
